url: https://jagacademy.github.io
baseurl: #

# Site settings
title: jag academy
email: agarciafdz@gmail.comk
description: "Centro de Entrenamiento basado en métodos ágiles Kanban, Scrum"


# Team names, titles and social links
people:
- name: Pepe Hernández R.
  pic: 1
  position: Consultor Líder
  social:
    - title: twitter
      url: https://twitter.com/pphdez76
    - title: facebook
      url: https://www.facebook.com/pphdez76
    - title: blogger
      url: http://novador.blogspot.mx/

- name: Alejandro García Fernández
  pic: 2
  position: Consultor líder
  social:
    - title: twitter
      url: https://twitter.com/agarciafdz
    - title: facebook
      url: https://www.facebook.com/elviejo79
    - title: linkedin
      url: https://www.linkedin.com/in/elviejo79/


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Gavilanes 153, Los Gavilanes
  - line: Guadalupe, Zacatecas, CP 98619

# Build settings
markdown: kramdown
permalink: pretty
